### ISSUE TITLE
Groq-Laravel doesn't work on windows

### ISSUE THREAD

**Issue by georgerabus** [lucianotonet/groq-laravel#3] opened 2024-10-01 13:01 UTC
I have a linux machine where I work but wanted to test on windows also, nothing works. Did a lot of debugging at it stops working here:

```
    private function query($predefinedPrompt) {
        $chatCompletion = Groq::chat()->completions()->create([
            "model" => "llama-3.2-90b-text-preview",
            'messages' => [
                ['role' => 'user', 'content' => $predefinedPrompt],
            ],
        ]);
        
        Log::info('Groq response: ', $chatCompletion);
        return $chatCompletion['choices'][0]['message']['content'];
    }
```

laravel.log just throws this: [2024-10-01 12:55:51] local.ERROR: Groq exception: Unknown error

**Comment by lucianotonet** [comment] 2024-10-01 23:11
@georgerabus 

I'm on a Windows machine trying to reproduce the error with the information provided, but so far, I haven't gotten the Unknown error.

In order for me to help you, I need you to:
- Check that there is no `GROQ_API_BASE_URL` or `GROQ_API_BASE` environment variable on your Windows. If there are, remove or overwrite them via the `.env` file with the value "https://api.groq.com/openai/v1"
- Make sure Llama-3.2 version 90b is available for your account
- Make sure you have not exceeded the quota limits of the selected model

**Comment by georgerabus** [comment] 2024-10-07 14:20
> @georgerabus
> 
> I'm on a Windows machine trying to reproduce the error with the information provided, but so far, I haven't gotten the Unknown error.
> 
> In order for me to help you, I need you to:
> 
>     * Check that there is no `GROQ_API_BASE_URL` or `GROQ_API_BASE` environment variable on your Windows. If there are, remove or overwrite them via the `.env` file with the value "https://api.groq.com/openai/v1"
> 
>     * Make sure Llama-3.2 version 90b is available for your account
> 
>     * Make sure you have not exceeded the quota limits of the selected model

all of these where checked. I copied the same .env file from linux to unix, including with the GROQ_API_BASE_URL and GROQ_API_BASE environment variable.

**Comment by lucianotonet** [comment] 2024-10-07 23:00
It seems to be a very specific issue just on your environment and as I have no other bugs like this reported, I will consider it as not related with the package itself. 

I will close this issue, but I still want to help you, so you can reach me out via email <tonetlds@gmail.com> or any other channel, so we can schedule an one-to-one meet and check out what is happening.

**Closed as completed by lucianotonet** 2024-10-07 23:00 UTC
